# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=django_fields.fields.DefaultStaticImageField(blank=True, upload_to=''),
        ),
    ]
