# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0002_auto_20190308_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='recipe',
            new_name='recipe_name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipe_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='recipe',
            new_name='recipe_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recipe_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='breakfast.Favourites'),
            preserve_default=False,
        ),
    ]
