# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0003_auto_20190320_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to=''),
        ),
    ]
