# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfast', '0008_auto_20190320_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='recipe_pic'),
            preserve_default=False,
        ),
    ]
